--auto-generated by ps packet tool, do not modify
--CGChongLou
--Author LiuZhen

--重楼装备操作
local CGChongLou = class("CGChongLou", LuaRequestPacket)

function CGChongLou:Init()
	self:SetupGameServerPacket(3108)
	self.operateType = 0
	self.equipPos = 0
	self.bagPos = 0
end

function CGChongLou:WriteStream()
	--操作类型（0=查询列表，1=打造， 2=觉醒， 3=继承）
	self:WriteInt32(self.operateType)
	--装备位
	self:WriteInt32(self.equipPos)
	--背包位 继承时使用
	self:WriteInt32(self.bagPos)
	if(AddWatch ~= nil) then
		AddWatch(LiuZhen)
	end
end

return CGChongLou