--auto-generated by ps packet tool, do not modify
--GCChongLou

--重楼返回
local GCChongLou = class("GCChongLou", LuaResponsePacket)

function GCChongLou:ReadStream()
	--推送原因（0=查询列表，1=打造，2=觉醒，3=继承）
	self.syncType = self:ReadInt32()
	--返回的装备个数，如果是更新可能只有一个	
	self.listCount = self:ReadByte()
	--返回的装备详细信息
	self.listArray = {}
	for i = 1, self.listCount do
		self.listArray[i] = {}
		self.listArray[i].equipPos = self:ReadByte()
		self.listArray[i].state = self:ReadByte()
	end
	if(AddWatch ~= nil) then
		AddWatch()
	end
end

function GCChongLou:Handler()
	Log.Info("GCChongLou:Handler...")
end

return GCChongLou